apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: librechat-dev-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: purpose
              operator: In
              values:
                - development
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: librechat
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: librechat t
                  namespace: librechat
                  path: librechat
                  placementName: librechat-dev-placement 
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: "{{placementName}}"
              requeueAfterSeconds: 30
  template:
    metadata:
      name: "{{appName}}-{{name}}"
      labels:
        velero.io/exclude-from-backup: "true"
        app.kubernetes.io/part-of: application-lifecycle
        app.kubernetes.io/managed-by: argocd
        apps.open-cluster-management.io/cluster-set: global
        cluster.open-cluster-management.io/placement: "{{placementName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/maximilianoPizarro/ia-developement-gitops.git
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - helm-values.yaml
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
