apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moodle-develop
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/maximilianoPizarro/moodle-gitops.git
    targetRevision: main
    path: overlay/develop
  destination:
    server: https://kubernetes.default.svc
    namespace: moodle-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
