---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: moodle
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - env: develop
            path: overlay/develop
            namespace: moodle-dev
          - env: production
            path: overlay/production
            namespace: moodle-prod
  template:
    metadata:
      name: moodle-{{env}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      project: default
      source:
        repoURL: https://github.com/maximilianoPizarro/moodle-gitops
        targetRevision: main
        path: "{{path}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true