apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: moodle
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: develop
                  path: overlay/develop
                  namespace: moodle-dev
                  placementName: moodle-dev-placement
                - env: production
                  path: overlay/production
                  namespace: moodle-prod
                  placementName: moodle-prod-placement
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: "{{placementName}}"
              requeueAfterSeconds: 180
  template:
    metadata:
      name: moodle-{{env}}-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      project: default
      source:
        repoURL: https://github.com/maximilianoPizarro/moodle-gitops
        targetRevision: main
        path: "{{path}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: moodle-dev-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: purpose
              operator: In
              values:
                - dev
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: moodle-prod-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: purpose
              operator: In
              values:
                - prod
