apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "moodle"
  description: "Moodle for Red Hat Developer Hub"
  annotations:
  annotations:
    quay.io/repository-slug: maximilianopizarro/moodle
    github.com/project-slug: maximilianopizarro/moodle-gitops
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: moodle-dev
    backstage.io/kubernetes-id: moodle
    janus-idp.io/tekton : moodle
    backstage.io/kubernetes-label-selector: 'app=moodle'
  links:
    - title: Documentation
      url: https://github.com/maximilianoPizarro/moodle-gitops/blob/main/README.md 
    - url: https://workspaces.openshift.com/#https://github.com/maximilianopizarro/moodle-gitops
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://moodle-maximilianopizar-2-dev.apps.rm2.thpm.p1.openshiftapps.com
      title: Moodle Url
      icon: web
  tags:
    - template
    - tekton
    - moodle
    - dev      
spec:
  type: webside
  lifecycle: experimental
  owner: "user:default/mapizarr"
