apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./route.yaml
  - ../../base
  - ./pipelinetask.yaml
  - ./pipeline.yaml
  - ./pipelinerun.yaml

patches:
  - path: ./deployment-patches.yaml