apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  template:
    spec:
      volumes:
        - name: moodle-data
          persistentVolumeClaim:
            claimName: moodle-data
        - name: moodle-configuration-volume
          configMap:
            name: moodle-configuration
            defaultMode: 420   
      containers:
      - name: moodle
        image: quay.io/maximilianopizarro/moodle:latest
        env:
          - name: NAMESPACE
            value: 'moodle-prod'
          - name: EXTERNAL_URL
            value: https://moodle-moodle-prod.apps.cluster-d5djr-2.d5djr-2.sandbox1236.opentlc.com
        volumeMounts:
          - name: moodle-data
            mountPath: /opt/app-root/moodledata
          - name: moodle-configuration-volume
            mountPath: /opt/app-root/src/config.php
            subPath: config.php      
