kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: moodle
  labels:
    app.kubernetes.io/instance: moodle
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle      
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/maximilianopizarro/moodle:latest
      importPolicy:
        scheduled: true
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: php-74
  labels:
    app.kubernetes.io/instance: moodle
    app.kubernetes.io/name: moodle
    app.kubernetes.io/part-of: moodle      
spec:
  lookupPolicy:
    local: false

