apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moodle-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: moodle-dev
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
      kind: ServiceAccount
  project: default
  source:
    repoURL: https://github.com/maximilianoPizarro/moodle-gitops.git
    targetRevision: main
    path: overlay/develop
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true