apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: moodle-pipelinerun
  labels:
    app: moodle
    tekton.dev/pipeline: moodle
spec:
  params:
    - name: APP_NAME
      value: moodle
    - name: GIT_REPO
      value: 'https://github.com/moodle/moodle'
    - name: GIT_REVISION
      value: MOODLE_311_STABLE
    - name: IMAGE_NAME
      value: 'image-registry.openshift-image-registry.svc:5000/moodle-dev/moodle'
    - name: PATH_CONTEXT
      value: .
    - name: VERSION
      value: moodle-dev/php-74
    - name: EXTERNAL_URL
      value: moodle-moodle-dev.apps.cluster-cf2j7.cf2j7.sandbox519.opentlc.com
  pipelineRef:
    name: moodle
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: moodle-workspace